<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php if ($this->pageCount): ?>
<div class="paginationControl">
<!-- <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> -->
总共 <?php echo $this->totalItemCount; ?> 条

<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->first)); ?>">
    第一页
  </a> |
<?php else: ?>
  <span class="disabled">第一页</span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
    &lt; 上一页
  </a> |
<?php else: ?>
  <span class="disabled">&lt; 上一页</span> |
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
    下一页  &gt;
  </a> |
<?php else: ?>
  <span class="disabled">下一页 &gt;</span> |
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url($this->route, array('page' => $this->last)); ?>">
    最后一页
  </a>
<?php else: ?>
  <span class="disabled">最后一页</span>
<?php endif; ?>

</div>
<?php endif; ?>